# YOLOv5 Export Configuration

model:
  weights: "models/yolov5/yolov5s.pt"   # Path to trained YOLOv5 weights
  input_size: [640, 640]                 # Input resolution (H, W)
  batch_size: 1                          # Batch size during export
  opset_version: 12                      # ONNX opset version
  include: ["onnx"]                      # Export format(s)

output:
  onnx_path: "models/onnx/yolov5s.onnx"  # Path where ONNX model will be saved
  simplify: true                         # Apply graph simplification
